version: "3"

networks:
  basicgoapp:
    driver: bridge

services:
  app-air:
    networks:
      - basicgoapp
    image: cosmtrek/air
    working_dir: "/usr/src/app"
    ports:
      - 8001:8000
    environment:
      TODO: "update"
    volumes:
      - "./:/usr/src/app"

  kafka:
    networks:
      - basicgoapp
    image: "bitnami/kafka:latest"
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      
    depends_on:
      - zookeeper
  zookeeper:
    networks:
      - basicgoapp
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
